[2024-05-06T11:56:35.391+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-06T11:56:35.415+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_operator_dag.populate_pet_table_pgsql manual__2024-05-06T11:29:02.907851+00:00 [queued]>
[2024-05-06T11:56:35.423+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_operator_dag.populate_pet_table_pgsql manual__2024-05-06T11:29:02.907851+00:00 [queued]>
[2024-05-06T11:56:35.424+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 3
[2024-05-06T11:56:35.436+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): populate_pet_table_pgsql> on 2024-05-06 11:29:02.907851+00:00
[2024-05-06T11:56:35.442+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1872) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-06T11:56:35.443+0000] {standard_task_runner.py:63} INFO - Started process 1874 to run task
[2024-05-06T11:56:35.443+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'populate_pet_table_pgsql', 'manual__2024-05-06T11:29:02.907851+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/kachevo.py', '--cfg-path', '/tmp/tmpw5c18f8q']
[2024-05-06T11:56:35.445+0000] {standard_task_runner.py:91} INFO - Job 161: Subtask populate_pet_table_pgsql
[2024-05-06T11:56:35.481+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_operator_dag.populate_pet_table_pgsql manual__2024-05-06T11:29:02.907851+00:00 [running]> on host db2363de7199
[2024-05-06T11:56:35.553+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_operator_dag' AIRFLOW_CTX_TASK_ID='populate_pet_table_pgsql' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T11:29:02.907851+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T11:29:02.907851+00:00'
[2024-05-06T11:56:35.554+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-06T11:56:35.565+0000] {sql.py:276} INFO - Executing: 
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Max', 'Dog', '2018-07-05', 'Jane');
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Susie', 'Cat', '2019-05-01', 'Phil');
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Lester', 'Hamster', '2020-06-23', 'Lily');
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Quincy', 'Parrot', '2013-08-11', 'Anne');
            
[2024-05-06T11:56:35.574+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-05-06T11:56:35.582+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-05-06T11:56:35.624+0000] {sql.py:457} INFO - Running statement: 
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Max', 'Dog', '2018-07-05', 'Jane');
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Susie', 'Cat', '2019-05-01', 'Phil');
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Lester', 'Hamster', '2020-06-23', 'Lily');
            INSERT INTO pet (name, pet_type, birth_date, OWNER)
            VALUES ( 'Quincy', 'Parrot', '2013-08-11', 'Anne');
            , parameters: None
[2024-05-06T11:56:35.627+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-06T11:56:35.628+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: ОШИБКА:  отношение "pet" не существует
LINE 2:             INSERT INTO pet (name, pet_type, birth_date, OWN...
                                ^

[2024-05-06T11:56:35.636+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_operator_dag, task_id=populate_pet_table_pgsql, execution_date=20240506T112902, start_date=20240506T115635, end_date=20240506T115635
[2024-05-06T11:56:35.646+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 161 for task populate_pet_table_pgsql (ОШИБКА:  отношение "pet" не существует
LINE 2:             INSERT INTO pet (name, pet_type, birth_date, OWN...
                                ^
; 1874)
[2024-05-06T11:56:35.657+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-06T11:56:35.665+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class MySqlOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-05-06T11:56:35.666+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-05-06T11:56:35.681+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-06T11:56:35.682+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
