[2024-05-05T15:23:27.327+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T15:23:27.348+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_operator_dag.getfrommysql manual__2024-05-05T15:23:20.192525+00:00 [queued]>
[2024-05-05T15:23:27.356+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_operator_dag.getfrommysql manual__2024-05-05T15:23:20.192525+00:00 [queued]>
[2024-05-05T15:23:27.357+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-05T15:23:27.369+0000] {taskinstance.py:2327} INFO - Executing <Task(MySqlOperator): getfrommysql> on 2024-05-05 15:23:20.192525+00:00
[2024-05-05T15:23:27.376+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1164) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-05T15:23:27.377+0000] {standard_task_runner.py:63} INFO - Started process 1165 to run task
[2024-05-05T15:23:27.377+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'getfrommysql', 'manual__2024-05-05T15:23:20.192525+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/kachevo.py', '--cfg-path', '/tmp/tmplragzpdh']
[2024-05-05T15:23:27.379+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask getfrommysql
[2024-05-05T15:23:27.419+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_operator_dag.getfrommysql manual__2024-05-05T15:23:20.192525+00:00 [running]> on host db2363de7199
[2024-05-05T15:23:27.496+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_operator_dag' AIRFLOW_CTX_TASK_ID='getfrommysql' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T15:23:20.192525+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T15:23:20.192525+00:00'
[2024-05-05T15:23:27.497+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T15:23:27.507+0000] {sql.py:276} INFO - Executing: select * from pet where name = "Samurai"
[2024-05-05T15:23:27.516+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-05-05T15:23:27.527+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-05-05T15:23:27.595+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T15:23:27.596+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 195, in get_conn
    return MySQLdb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
[2024-05-05T15:23:27.606+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=postgres_operator_dag, task_id=getfrommysql, execution_date=20240505T152320, start_date=20240505T152327, end_date=20240505T152327
[2024-05-05T15:23:27.617+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 45 for task getfrommysql ((1045, "Access denied for user 'root'@'localhost' (using password: YES)"); 1165)
[2024-05-05T15:23:27.631+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T15:23:27.645+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T15:23:27.647+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
