[2024-05-06T11:56:24.371+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-06T11:56:24.391+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_operator_dag.send_email_on_error manual__2024-05-06T11:29:02.907851+00:00 [queued]>
[2024-05-06T11:56:24.399+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_operator_dag.send_email_on_error manual__2024-05-06T11:29:02.907851+00:00 [queued]>
[2024-05-06T11:56:24.400+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-06T11:56:24.414+0000] {taskinstance.py:2327} INFO - Executing <Task(EmailOperator): send_email_on_error> on 2024-05-06 11:29:02.907851+00:00
[2024-05-06T11:56:24.419+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1867) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-06T11:56:24.421+0000] {standard_task_runner.py:63} INFO - Started process 1870 to run task
[2024-05-06T11:56:24.421+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'send_email_on_error', 'manual__2024-05-06T11:29:02.907851+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/kachevo.py', '--cfg-path', '/tmp/tmp1ottas9r']
[2024-05-06T11:56:24.423+0000] {standard_task_runner.py:91} INFO - Job 159: Subtask send_email_on_error
[2024-05-06T11:56:24.462+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_operator_dag.send_email_on_error manual__2024-05-06T11:29:02.907851+00:00 [running]> on host db2363de7199
[2024-05-06T11:56:24.549+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_operator_dag' AIRFLOW_CTX_TASK_ID='send_email_on_error' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T11:29:02.907851+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T11:29:02.907851+00:00'
[2024-05-06T11:56:24.550+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-06T11:56:24.573+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-05-06T11:56:24.574+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-05-06T11:56:24.574+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-05-06T11:56:24.576+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-06T11:56:24.576+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 273, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 317, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 852, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/socket.py", line 837, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[2024-05-06T11:56:24.586+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=postgres_operator_dag, task_id=send_email_on_error, execution_date=20240506T112902, start_date=20240506T115624, end_date=20240506T115624
[2024-05-06T11:56:24.599+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 159 for task send_email_on_error ([Errno 111] Connection refused; 1870)
[2024-05-06T11:56:24.635+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-06T11:56:24.651+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-06T11:56:24.653+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
