[2024-05-06T10:00:40.217+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-06T10:00:40.235+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_operator_dag.getfrommysql manual__2024-05-06T10:00:34.412389+00:00 [queued]>
[2024-05-06T10:00:40.242+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_operator_dag.getfrommysql manual__2024-05-06T10:00:34.412389+00:00 [queued]>
[2024-05-06T10:00:40.243+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-06T10:00:40.254+0000] {taskinstance.py:2327} INFO - Executing <Task(MySqlOperator): getfrommysql> on 2024-05-06 10:00:34.412389+00:00
[2024-05-06T10:00:40.260+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=130) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-06T10:00:40.261+0000] {standard_task_runner.py:63} INFO - Started process 131 to run task
[2024-05-06T10:00:40.261+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'getfrommysql', 'manual__2024-05-06T10:00:34.412389+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/kachevo.py', '--cfg-path', '/tmp/tmprhbha_yz']
[2024-05-06T10:00:40.263+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask getfrommysql
[2024-05-06T10:00:40.295+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_operator_dag.getfrommysql manual__2024-05-06T10:00:34.412389+00:00 [running]> on host db2363de7199
[2024-05-06T10:00:40.366+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_operator_dag' AIRFLOW_CTX_TASK_ID='getfrommysql' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T10:00:34.412389+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-06T10:00:34.412389+00:00'
[2024-05-06T10:00:40.368+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-06T10:00:40.379+0000] {sql.py:276} INFO - Executing: select * from pet where name = "Samurai"
[2024-05-06T10:00:40.387+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-05-06T10:00:40.394+0000] {base.py:84} INFO - Using connection ID 'mysql' for task execution.
[2024-05-06T10:00:40.412+0000] {sql.py:457} INFO - Running statement: select * from pet where name = "Samurai", parameters: None
[2024-05-06T10:00:40.414+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-06T10:00:40.414+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1046, 'No database selected')
[2024-05-06T10:00:40.423+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=postgres_operator_dag, task_id=getfrommysql, execution_date=20240506T100034, start_date=20240506T100040, end_date=20240506T100040
[2024-05-06T10:00:40.435+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 52 for task getfrommysql ((1046, 'No database selected'); 131)
[2024-05-06T10:00:40.475+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-06T10:00:40.488+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-06T10:00:40.490+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
