[2024-05-05T13:22:48.366+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-05T13:22:48.409+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_operator_dag.create_pet_table manual__2024-05-05T13:22:47.164802+00:00 [queued]>
[2024-05-05T13:22:48.421+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_operator_dag.create_pet_table manual__2024-05-05T13:22:47.164802+00:00 [queued]>
[2024-05-05T13:22:48.423+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-05T13:22:48.445+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2024-05-05 13:22:47.164802+00:00
[2024-05-05T13:22:48.453+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=231) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-05T13:22:48.455+0000] {standard_task_runner.py:63} INFO - Started process 232 to run task
[2024-05-05T13:22:48.456+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_operator_dag', 'create_pet_table', 'manual__2024-05-05T13:22:47.164802+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/kachevo.py', '--cfg-path', '/tmp/tmpsmgrus5j']
[2024-05-05T13:22:48.460+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask create_pet_table
[2024-05-05T13:22:48.526+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_operator_dag.create_pet_table manual__2024-05-05T13:22:47.164802+00:00 [running]> on host db2363de7199
[2024-05-05T13:22:48.632+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_operator_dag' AIRFLOW_CTX_TASK_ID='create_pet_table' AIRFLOW_CTX_EXECUTION_DATE='2024-05-05T13:22:47.164802+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-05T13:22:47.164802+00:00'
[2024-05-05T13:22:48.633+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-05T13:22:48.652+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS pet (
            pet_id SERIAL PRIMARY KEY,
            name VARCHAR NOT NULL,
            pet_type VARCHAR NOT NULL,
            birth_date DATE NOT NULL,
            OWNER VARCHAR NOT NULL);
          
[2024-05-05T13:22:48.663+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-05T13:22:48.674+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2024-05-05T13:22:48.682+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=postgres_operator_dag, task_id=create_pet_table, execution_date=20240505T132247, start_date=20240505T132248, end_date=20240505T132248
[2024-05-05T13:22:48.698+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 23 for task create_pet_table (The conn_id `postgres_default` isn't defined; 232)
[2024-05-05T13:22:48.711+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-05T13:22:48.723+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-05-05T13:22:48.736+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-05T13:22:48.741+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
